### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by cordoval** [rollerworks/RollerworksSearch#66]
- [x] regarding rollerworks search symfony validator package, is its use only limited to validating services of the library? can you please clarify?

- [x] how close are lexikfilter and rollerworks search, currently we are needing filters and since datagrid concern is separate we are about to engage in using lexikfitler, will there be some support via rollerwork search and how this will support materialize, which is the support architecture that it will have?

- [x] old RollerworksRecordFilterBundle has now turned into RollerworksSearch, i will plug both rollerworks search bundle and lexik bundle and i hope there is a transition we can do?

- [x]  The readme is fabulous and better than lexik but how much of this is implemented and working well, i am about to put it into production and need to know for sure.

**Comment by sstok** [comment]
> regarding rollerworks search symfony validator package, is its use only limited to validating services of the library? can you please clarify?

The library is used to validate a SearchCondition by constraints, much like as you validate a form.
The value maybe properly formatted, but the value can be limited (text, but must not contain any spaces).

>  how close are lexikfilter and rollerworks search, currently we are needing filters and since datagrid concern is separate we are about to engage in using lexikfitler, will there be some support via rollerwork search and how this will support materialize, which is the support architecture that it will have?

Both target the same but use a different approach, the LexikFilterBundle works with forms and modifies the the Doctrine Query object. RollerworksSearch transforms input from any source (InputProcessor) into a SearchCondition, the `SearchCondition` is then used by another library to search in a data source (like an relational Database or ElasticSearch).

Plus, a SearchCondition can hold very complex conditions like logical groups (`WHERE (user = 1) OR (name='who')` as in SQL) and be optimized to remove duplicate/redundant values.

Because the SearchCondition is not limited to a single data source its more flexible then the LexikFilterBundle and provides a better performance thanks to caching of processed results!

>  old RollerworksRecordFilterBundle has now turned into RollerworksSearch, i will plug both rollerworks search bundle and lexik bundle and i hope there is a transition we can do?

The RollerworksRecordFilterBundle is pretty much dead, RollerworksSearch is a complete rewrite of the source and provides much more flexibility and quality.

*RollerworksRecordFilterBundle was originally written as part of the RollerworkFramework but was overly complicated and badly designed as it was my very first Symfony bundle.* I'm actually planning on removing the repository very soon.

>  The readme is fabulous and better than lexik but how much of this is implemented and working well, i am about to put it into production and need to know for sure.

Everything is will tested and considered production ready (in fact the tests are properly the best of Rollerworks projects), the mean reason why I didn't release a 1.0.0 version yet is because some things changed recently in an backward incompatible manner.

And the SearchProcessor is giving me a headache, when I find something thats blocking I need to be able to change this :) as PSR-7 is accepted now it should be easier to implement this without making it Symfony only.
